### ISSUE TITLE
Addon not working on 4.2.f

### ISSUE THREAD

**Issue by douglascrp** [deas/contentreich-alfresco-datalists#26]
Hey @deas 

I tried your addon, the new version 1.4.3 on a 4.2.f Alfresco server, but I see nothing "new".
Is it supposed to work by simply dropping the generated jars inside the right folders?
Should I see the "filter screen" for every single datalist I already have or new ones I create after the addon install?
How about the example xml file? Is it a requirement to make it work?
I tried to configure it using my custom datalist type as described by the comments inside the file, but even with that, I saw nothing new.
I know the configuration is being loaded, because I accidentally put some wrong config, and Alfresco complained about those.

Can you help me with that?

**Comment by deas** [comment]
I have  not tried it on 4.2, but I  guess it should work.

Yes, you install by just  dropping the jars inside the proper folders. Make sure to enable the module at http://localhost:8080/share/page/modules/deploy . That should make the filters appear for the  lists shipping with Alfresco.

What's new  here is that the extension no longer  overrides all sorts of stuff - especially regarding  the model. So I expect it to cause way less problems. In fact I even removed functionality, so its  pretty much only the filters now. We may introduce custom lists/properties again, but I do not want to override any core functionality.

**Comment by douglascrp** [comment]
Ah, really? LOL
I didn't know about the module deploy... How could I forget to look at it...
Well, I'm going to try and let you know the result.

Thank you so much for the quick answer.

**Comment by douglascrp** [comment]
@deas the module deploy did the trick.
Thank you
