### ISSUE TITLE
Include the download datalist as xml action

### ISSUE THREAD

**Issue by douglascrp** [deas/contentreich-alfresco-datalists#28]
How about including the download datalist as xls action?

**Comment by deas** [comment]
The project had its own xls export Java class which was not really needed. Actually, I wanted to retain the functionality, but looks like it got lost. Should be fairly easy to get it back. Will look into that.

**Comment by deas** [comment]
Version 1.4.4 brings back xls export.

**Comment by douglascrp** [comment]
Thank you
