### ISSUE TITLE
Properties files import not working

### ISSUE THREAD

**Issue by douglascrp** [deas/contentreich-alfresco-datalists#30]
@deas I'm facing some problems with the localization properties files not being loaded.

Both 
```
surf.include.resources=org/alfresco/components/data-lists/toolbar.get
```
and 
```
surf.include.resources=org/alfresco/components/data-lists/datagrid.get
```
into toolbar.get.propertiesand datagrid.get.properties

**Comment by deas** [comment]
This is most likely because you are running the extension of 4.x. If we really want/need to support that, I suggest we create a separate branch.

**Comment by douglascrp** [comment]
I guess you are right about the 4.x limitation.
I've just tried to find any reference of **surf.include.resources** into the 4.2.f sources and found nothing.

I'm ok with the idea of keeping a new branch.
Can you create it?

**Comment by deas** [comment]
Done, just  forked from master. We can *caugh* copy the translations  there. I personally won't  be spending much time on Alfresco 4 support though.

**Comment by douglascrp** [comment]
Ok, no problem.
Let it with me.
I'm going to merge my changes tonight.

**Comment by deas** [comment]
The localization is merged already.
