### ISSUE TITLE
No Class Def Found Error

### ISSUE THREAD

**Issue by sl45sms** [deas/contentreich-alfresco-datalists#33]
Error creating bean with name 'webscript.de.fme.slingshot.datalists.list.get' defined in class path resource [alfresco/extension/fme/fme-extended-datalist-context.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/alfresco/service/cmr/i18n/MessageLookup

i get this on vanila Alfresco 4.2.b when fme-alfresco-extdl-repo-1.3.1.jar installed on tomcat/webapps/alfresco/WEB-INF/lib

is because missing messages folder and/or properties file?

**Comment by deas** [comment]
Not  sure about 4.2.b, but in 4.2.e, that class is in alfresco-data-model-4.2.e.jar.

You might want to check:

```
jar tvf alfresco-data-model-4.2.b.jar| grep org/alfresco/service/cmr/i18n/MessageLookup
```

Assuming the class is there, the only explanation I could  come up with is that the jar is in another location (e.g. tomcat/shared/lib) and that causes resolution to fail.

With that said, I would strongly recommend not to use  version 1.3 of the extension at all. On 4.2, you are  most likely best served building it from the  current 4.2.x branch.

**Comment by sl45sms** [comment]
you are right, there no i18n folder on alfresco-data-model-4.2.b.jar
i will try the 4.2.x branch
Thanks
