### ISSUE TITLE
"Reset" action button doesn't reset the form correctly

### ISSUE THREAD

**Issue by douglascrp** [deas/contentreich-alfresco-datalists#35]
After playing with the filter form a bit, we have noticed that the Reset button is not working correctly.
It seems the form is not completely ready, as, for example, the date-range control has not links configured on the calendar icon, making it impossible to select the date.

The problem happens both for 4.2.f and 5.0.d.

**Comment by iwkse** [comment]
Same here, I've just tested on 5.0.d and it's not possible to pick up a date from the icons, now links available.

**Comment by dgcloud** [comment]
For me this problem is happening  in 4.2.f. The calendar works well, but after I click the <clear data> it is unavailable. So I have to restart the data list.

**Comment by iwkse** [comment]
I've retried with latest git and I can confirm the behavior you're having as well. Sometimes it works but after clicking reset filter it stops too work. Not only the calendar, in some occasion the filtering didn't happen as well.

**Comment by deas** [comment]
`this.formsRuntime.reset();`  can still blow up due to an invalid form id. Only  god know where it picks it  up.
